.TH SUPER-STUPID-HTTP-SERVER 1 "Октябрь 2023" "1.0" "Руководство пользователя"
.SH ИМЯ
super-stupid-http-server \- Простой многопоточный HTTP сервер с решением проблемы 10K
.SH СИНТАКСИС
.B super-stupid-http-server
.RI
.SH ОПИСАНИЕ
.B super-stupid-http-server
Это простой HTTP сервер, реализованный на C++, который поддерживает многопоточность и решает проблему 10K клиентов. Он прослушивает порт 8080 по умолчанию и отвечает "Hello, World!" на любые GET запросы.
.SH ОПЦИИ
Для этого сервера не предусмотрены опции.
.SH СМ. ТАКЖЕ
.BR curl (1),
.BR netstat (8),
.BR kill (1)
.SH АВТОР
Просвирнин С.Д.
